site_name: Josias Rico - Technical Writer
nav:
  - About: about.md
  - Skills: techskills.md
  - Background: 'background.md'
  
theme:
  name: material
  logo: images/wizeline_isotype.png

extra_css:
  - css/extra.css